from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional

import config
from features.staff.departmentOrbat.layouts import loadDepartmentLayouts

_defaultCredentialsPathEnvVar = "ORBAT_GOOGLE_CREDENTIALS_PATH"
_defaultCredentialsPathConfigKey = "orbatGoogleCredentialsPath"


@dataclass(frozen=True)
class MultiOrbatSheetConfig:
    key: str
    displayName: str
    spreadsheetId: str
    sheetName: str
    credentialsPathEnvVar: str = "ORBAT_GOOGLE_CREDENTIALS_PATH"
    credentialsPathConfigKey: str = "orbatGoogleCredentialsPath"
    rowModel: Dict[str, Any] = field(default_factory=dict)
    organization: Dict[str, Any] = field(default_factory=dict)
    formatting: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)


def _asDict(raw: Any) -> dict[str, Any]:
    return raw if isinstance(raw, dict) else {}


def _asText(raw: Any, fallback: str = "") -> str:
    value = str(raw or "").strip()
    return value if value else fallback


def _normalizeSheetConfig(raw: dict[str, Any]) -> Optional[MultiOrbatSheetConfig]:
    key = _asText(raw.get("key"))
    spreadsheetId = _asText(raw.get("spreadsheetId"))
    sheetName = _asText(raw.get("sheetName"))
    if not key or not spreadsheetId or not sheetName:
        return None

    displayName = _asText(raw.get("displayName"), key)
    return MultiOrbatSheetConfig(
        key=key,
        displayName=displayName,
        spreadsheetId=spreadsheetId,
        sheetName=sheetName,
        credentialsPathEnvVar=_asText(
            raw.get("credentialsPathEnvVar"),
            _defaultCredentialsPathEnvVar,
        ),
        credentialsPathConfigKey=_asText(
            raw.get("credentialsPathConfigKey"),
            _defaultCredentialsPathConfigKey,
        ),
        rowModel=_asDict(raw.get("rowModel")),
        organization=_asDict(raw.get("organization")),
        formatting=_asDict(raw.get("formatting")),
        metadata=_asDict(raw.get("metadata")),
    )


def _baseSheetEntry(
    *,
    key: str,
    displayName: str,
    spreadsheetId: str,
    sheetName: str,
) -> dict[str, Any]:
    return {
        "key": key,
        "displayName": displayName,
        "spreadsheetId": spreadsheetId,
        "sheetName": sheetName,
        "credentialsPathEnvVar": _defaultCredentialsPathEnvVar,
        "credentialsPathConfigKey": _defaultCredentialsPathConfigKey,
    }


def _fallbackRegistry() -> list[dict[str, Any]]:
    return [
        _baseSheetEntry(
            key="generalStaff",
            displayName="General Staff ORBAT",
            spreadsheetId=getattr(config, "orbatSpreadsheetId", ""),
            sheetName=getattr(config, "orbatSheetName", "General Staff"),
        ),
        _baseSheetEntry(
            key="recruitment",
            displayName="Recruitment ORBAT",
            spreadsheetId=getattr(config, "recruitmentSpreadsheetId", ""),
            sheetName="ANRORS",
        ),
    ]


def _buildDepartmentRegistryFromLayouts() -> list[dict[str, Any]]:
    spreadsheetId = _asText(getattr(config, "deptSpreadsheetId", ""))
    if not spreadsheetId:
        return []

    entries: list[dict[str, Any]] = []
    for layout in loadDepartmentLayouts():
        if not isinstance(layout, dict):
            continue
        sheetKey = _asText(layout.get("sheetKey"))
        sheetName = _asText(layout.get("sheetName"))
        if not sheetKey or not sheetName:
            continue

        divisionKey = _asText(layout.get("divisionKey"))
        displayName = _asText(layout.get("displayName"), f"Department ORBAT - {divisionKey or sheetName}")
        supportsSectionHeaders = bool(layout.get("sectionHeaders"))
        entry = _baseSheetEntry(
            key=sheetKey,
            displayName=displayName,
            spreadsheetId=spreadsheetId,
            sheetName=sheetName,
        )
        entry["organization"] = {
            "enabled": True,
            "supportsSectionHeaders": supportsSectionHeaders,
        }
        entry["metadata"] = {
            "divisionKey": divisionKey,
            "autoGenerated": True,
        }
        entries.append(entry)
    return entries


def loadMultiOrbatRegistry() -> dict[str, MultiOrbatSheetConfig]:
    rawRegistry = getattr(config, "multiOrbatSheets", None)
    if not isinstance(rawRegistry, list) or not rawRegistry:
        rawRegistry = _fallbackRegistry()
    else:
        rawRegistry = [entry for entry in rawRegistry if isinstance(entry, dict)]

    existingKeys = {
        _asText(entry.get("key"))
        for entry in rawRegistry
        if isinstance(entry, dict)
    }
    for generatedEntry in _buildDepartmentRegistryFromLayouts():
        generatedKey = _asText(generatedEntry.get("key"))
        if generatedKey and generatedKey not in existingKeys:
            rawRegistry.append(generatedEntry)
            existingKeys.add(generatedKey)

    registry: dict[str, MultiOrbatSheetConfig] = {}
    for raw in rawRegistry:
        if not isinstance(raw, dict):
            continue
        parsed = _normalizeSheetConfig(raw)
        if not parsed:
            continue
        registry[parsed.key] = parsed
    return registry

